exports.vsfdleonardo = (id, A187, tampilTanggal, whatsapp, youtube, tampilWaktu, instagram, nomer, aktif) => {
	return ` 



 grrrrrrrrrrrrrrr 😡😡😡😡😡

   VAI SE FODER LEANDRO 
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   VAI SE FODER LEANDRO
   
   
   VAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDROVAI SE FODER LEANDRO`
}